## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
# Type your solution here
import pandas as pd
print("\nQ1-1")
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

df = pd.DataFrame(data) # creates data frame
print(df) 

print("\nQ1-2")
psych = df[(df["job"]== "psychologist") & (df["num_cars"]> df["family_size"])] # finds psychologists with num cars > fam size
teach = df[(df["job"]== "teacher") & (df["num_cars"]> df["family_size"])] # finds teachers with num cars > fam size

#combines
frames = [psych,teach] 
df2 = pd.concat(frames)
print(df2) # prints psychologist or teacher with num cars > fam size

print("\nQ1-3")
df3 = df[(df["family_size"] < 3) & (df["num_cars"]>0)] # selects at most 2 fam members and at least 1 car
print(df3)

print("\nQ1-4")
print(len(df.job.unique())) # gets num of unique jobs in data




Q1-1
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

Q1-2
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

Q1-3
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

Q1-4
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

means = weights.groupby(fruit).mean()
print(means) # prints mean of weights of each fruit

apple     1.0
banana    5.2
carrot    7.0
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
print("Q3-1")
ind = np.argsort(course_name) # finds indices
print(ind)

print("\nQ3-2")
words = np.char.startswith(course_name, "P") # finds char that starts with p
print(words)




Q3-1
[1 3 0 2 4]

Q3-2
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

print("Q4-1")
reverse = student_id[::-1] # reverses array
print(reverse)

print("\nQ4-2")
sortArray = np.argsort(student_id)
sort = student_id[sortArray] # sorts array
result = sort[-3: ] # finds 3 largest values
print(result)






Q4-1
[4532 5241 1682 1671 6230 5202 1023]

Q4-2
[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off

import numpy as np
x = np.arange(1, 100)
n= x[(x % 3 == 0) | (x % 5 == 0)] # finds multiples
#print(n[:1000])
print(n.sum()) # prints sum


2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [ ]:
# Type your solution here
import numpy as np

print("Q6-1")
arr = np.arange(12).reshape(3,4)
print("Original Array:")
print(arr)

arr[:, [1, 2]] = arr[:, [2, 1]] # swaps columns
print("Swapped Array:")
print(arr)

print("\nQ6-2")
arr = np.arange(12).reshape(3,4)
print("Original Array:")
print(arr)

arr[[0, 1],: ] = arr[[1, 0],:] # swaps rows
print("Swapped Array:")
print(arr)

Q6-1
Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped Array:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

Q6-2
Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped Array:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
